### ISSUE TITLE
Component names which contain 'end' break the generators

### ISSUE THREAD

**Issue by hl** [ecsx-framework/ECSx#74]
After you generate a component, e.g. `Legendary`, and it's added to the `components` list in the manager you are unable to generate any new components due to the mix task breaking on https://github.com/ecsx-framework/ECSx/blob/master/lib/mix/tasks/ecsx/helpers.ex#L50

**Comment by APB9785** [comment]
Hi @hl, thanks for your interest in ECSx, and for this bug report!  I see the problem, and there will be a patch coming soon to fix it.

**Comment by hl** [comment]
Thanks for the library, it's great and I can finally start on a game that I've been thinking about!

I can also give it a shot if you prefer.
