### ISSUE TITLE
`between` fails but `get_all` works for a numerical type.

### ISSUE THREAD

**Issue by hassanshaikley** [ecsx-framework/ECSx#78]
```
  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 5.1) :ets.select(Rotb.Components.Zone, [{{:"$1", :"$2", :_}, [{:>=, :"$2", -1}, {:"=<", :"$2", 1}], [{{:"$1", :"$2"}}]}])
    (ecsx 0.5.1) lib/ecsx/base.ex:114: ECSx.Base.between/3
```

When I use get_all/0 it works but when I use `between` it complains

`{player, _zone} <- Zone.between(zone_id - 1, zone_id + 1)` 

Is this a bug or am I doing something wrong?

**Comment by hassanshaikley** [comment]
It appears to work when I use the full name without the `alias`.

**Comment by hassanshaikley** [comment]
It started working then starting erroring again. Do you think it would be possible to quickly chat about this lib sometime? I'm interested in using it but seeing unexpected behavior.

**Comment by APB9785** [comment]
Hi @hassanshaikley and thanks for your interest in ECSx!  The ETS tables should be automatically created for you when the app starts, so I'm wondering if perhaps something went wrong with the setup process.  Can you share a repo which reproduces the issue?  I'd be happy to take a look.

**Comment by hassanshaikley** [comment]
https://github.com/hassanshaikley/rotb

on the ecsx branch!

**Comment by APB9785** [comment]
Hey Hassan, I checked out the link but it looks like the repo is private - I cannot access it.

Best way to reach me regarding ECSx is here in Github issues, so others can benefit from the results of our findings if the issue comes up again 🙂

**Comment by hassanshaikley** [comment]
I think it happens when an ets table is not public and I am trying to access it from within my channel. It's just odd that one method worked and another didn't! Also I might share a reproduction I'm just a little busy atm!

**Comment by APB9785** [comment]
Feel free to open this issue again if you are still having the issue.
